<?php

/**
 * @file
 * Contains landing page functionality for Lightning.
 */

use Drupal\field\FieldConfigInterface;
use Drupal\node\Entity\NodeType;
use Drupal\Core\Block\BlockPluginInterface;
use Drupal\Core\Entity\EntityDescriptionInterface;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Breadcrumb\Breadcrumb;
use Drupal\Core\Url;

/**
 * Implements hook_ENTITY_TYPE_insert().
 */
function ucr_news_articles_field_config_insert(FieldConfigInterface $field) {
  // Don't do anything during config sync.
  if (\Drupal::isConfigSyncing()) {
    return;
  }
}

/**
 * Implements hook_modules_installed().
 */
function ucr_news_articles_modules_installed(array $modules) {
  // Don't do anything during config sync.
  if (\Drupal::isConfigSyncing()) {
    return;
  }
}

function ucr_news_articles_menu_local_actions_alter(&$local_actions) {
}

/**
 * @param $view
 * Implements hook_views_post_render().
 * Used to update the title for the taxonomy view that is within the 'news_article_views' view.
 */
function ucr_news_articles_views_post_render($view) {
  $id = $view->id();
  if(strtolower($id) == "news_article_views") {
    $display = $view->current_display;
    if(strtolower($display) == "topics_news_list") {
        $title = $view->getTitle();
        if (is_numeric($title)) { // If the Taxonomy ID was passed, then get the name.
            $taxonomy_title = \Drupal\taxonomy\Entity\Term::load($title)->name->value;
        }
        else {
            $taxonomy_title = $title;
        }
        $new_title = "News Articles with Topic: ".$taxonomy_title;

        $view->setTitle($new_title);
    } elseif(strtolower($display) == "news_listing") {
        $route_params = \Drupal::routeMatch()->getParameters();
        $year = $route_params->get('arg_0');
        $month = $route_params->get('arg_1');
        $day = $route_params->get('arg_2');

        $appending_title = "";
        $day = (!is_numeric($day) ? "" : $day);
        $month = (!is_numeric($month) ? "" : $month);
        $year = (!is_numeric($year) ? "" : $year);
        if(!empty($day) && !empty($month) && !empty($year)) {
        $appending_title = " for ".date("F jS, Y", strtotime($year."-".$month."-".$day));
        } elseif(!empty($month) && !empty($year)) {
        $appending_title = " for ".date("F Y", strtotime($year."-".$month."-01"));
        } elseif(!empty($year)) {
        $appending_title = " for ".$year;
        }

        $view->setTitle("Latest News Articles" . $appending_title);
    }
  }
}

/**
 * Implements hook_system_breadcrumb_alter().
 */
function ucr_news_articles_system_breadcrumb_alter(Breadcrumb &$breadcrumb, RouteMatchInterface $route_match, array $context) {
  $route_name = $route_match->getRouteName();
  $links = $breadcrumb->getLinks();
  if($links) {
    $home_link = $links[0];
  } else {
    $home_link = array();
  }

  $types = array('view_id', 'taxonomy_term', 'node');
  $type_name = "";
  foreach($types as $type_to_try) {
    $route_type = $route_match->getParameter($type_to_try);
    if($route_type) {
      $type_name = $type_to_try;
      break;
    }
  }

  switch($type_name) {
    case "view_id": {
      $view_name = $route_match->getParameter('view_id');
      $view_display = $route_match->getParameter('display_id');

      // Check and validate for the Breadcrumbs for the News Listing View.
      if(($view_name == "news_article_views") && ($view_display == "news_listing")) {
        $year = $route_match->getParameter('arg_0');
        $month = $route_match->getParameter('arg_1');
        $day = $route_match->getParameter('arg_2');

        $appending_title = "";
        $day = (!is_numeric($day) ? "" : $day);
        $month = (!is_numeric($month) ? "" : $month);
        $year = (!is_numeric($year) ? "" : $year);
        if(!empty($day) && !empty($month) && !empty($year)) {
          $appending_title = " for ".date("F jS, Y", strtotime($year."-".$month."-".$day));
        } elseif(!empty($month) && !empty($year)) {
          $appending_title = " for ".date("F Y", strtotime($year."-".$month."-01"));
        } elseif(!empty($year)) {
          $appending_title = " for ".$year;
        }

        $new_links = array();
        $new_links[] = $home_link;
        if(!empty($appending_title)) {
          $new_links[] = \Drupal\Core\Link::fromTextAndUrl(t("Latest News"), Url::fromUserInput('/articles'));
          $new_links[] = \Drupal\Core\Link::createFromRoute(t("Articles".$appending_title), "<none>");
        } else {
          $new_links[] = \Drupal\Core\Link::createFromRoute(t("Latest News Articles"), "<none>");
        }
        $breadcrumb = new Breadcrumb();
        $breadcrumb->addCacheableDependency($route_name);
        $breadcrumb->setLinks($new_links);
      } elseif(($view_name == "taxonomy_term")) { // If the view is for the Taxonomy View.
        $taxonomy = $route_match->getParameter('taxonomy_term');
        $bundle = $taxonomy->bundle();

        // Only do this for the Topic's Taxonomy views.
        if(in_array($bundle, array("una_topic_category"))) {
          $new_links = array();
          $new_links[] = $home_link;
          $new_links[] = \Drupal\Core\Link::createFromRoute(t("News Articles with Topic: ".$taxonomy->name->value), "<none>");

          $breadcrumb = new Breadcrumb();
          $breadcrumb->addCacheableDependency($route_name);
          $breadcrumb->setLinks($new_links);
        }
      }
    break;
    }
    case "taxonomy_term": {
    break;
    }
    case "node": {
      $bundle = $route_type->bundle();

      // Modify the Breadcrumbs for the News Articles Content Type.
      if(($bundle == "news_articles") && ($route_name == "entity.node.canonical")) {
        $authored_date = $route_type->get('field_una_authored_on')->value;
        $new_links = array();
        $new_links[] = $home_link;
        $new_links[] = \Drupal\Core\Link::fromTextAndUrl(t("News"), Url::fromUserInput('/articles'));

        if(!empty($authored_date)) {
          $year = date('Y', strtotime($authored_date));
          $month = date('m', strtotime($authored_date));
          $day = date('d', strtotime($authored_date));
          $display_date = date('F jS, Y', strtotime($authored_date));
          $new_links[] = \Drupal\Core\Link::fromTextAndUrl(t($display_date), Url::fromUserInput('/articles/'.$year."/".$month."/".$day));
        }
        $new_links[] = \Drupal\Core\Link::createFromRoute(t($route_type->get('title')->value), "<none>");

        $breadcrumb = new Breadcrumb();
        $breadcrumb->addCacheableDependency($route_name);
        $breadcrumb->setLinks($new_links);
      }
    break;
    }
  }
}

function ucr_news_articles_form_alter(&$form, $form_state, $form_id) {
  if (in_array($form_id, array('node_news_articles_form', 'node_news_articles_edit_form'))) {
    $form['una_author_info'] = [
      '#type' => 'details',
      '#title' => t('Article Author Info'),
      '#group' => 'advanced',
      '#attributes' => [
        'class' => ['node-form-options']
      ],
      '#attached' => [
        'library' => ['node/drupal.node'],
      ],
      '#weight' => 98,
      '#optional' => false,
      '#open' => false,
    ];

    $form['field_una_authored_by']['#group'] = 'una_author_info';
    $form['field_una_authored_on']['#group'] = 'una_author_info';

    $form['una_media_contacts'] = [
      '#type' => 'details',
      '#title' => t('Media Contacts'),
      '#group' => 'advanced',
      '#attributes' => [
        'class' => ['node-form-options']
      ],
      '#attached' => [
        'library' => ['node/drupal.node'],
      ],
      '#weight' => 99,
      '#optional' => true,
      '#open' => false,
    ];

    $form['field_una_media_contacts']['#group'] = 'una_media_contacts';

    $form['una_topic_tags'] = [
      '#type' => 'details',
      '#title' => t('Topic Category, Tags & Custom RSS'),
      '#group' => 'advanced',
      '#attributes' => [
        'class' => ['node-form-options']
      ],
      '#attached' => [
        'library' => ['node/drupal.node'],
      ],
      '#weight' => 100,
      '#optional' => true,
      '#open' => false,
    ];

    $form['field_una_topic_category']['#group'] = 'una_topic_tags';
    $form['field_una_tags']['#group'] = 'una_topic_tags';
    $form['field_una_custom_rss']['#group'] = 'una_topic_tags';

    $form['keywords'] = [
      '#type' => 'details',
      '#title' => t('Content Keywords'),
      '#group' => 'advanced',
      '#attributes' => [
        'class' => ['node-form-options']
      ],
      '#attached' => [
        'library' => ['node/drupal.node'],
      ],
      '#weight' => 101,
      '#optional' => true,
      '#open' => true,
    ];

    $form['field_content_keywords']['#group'] = 'keywords';

    // Programmatically change the Metatag values to be what they should be for the Articles.
    $config = \Drupal::configFactory();
    $meta_defaults = $config->get('metatag.metatag_defaults.node');
    $tags = $meta_defaults->get('tags');

    $modify_custom_metas = array(
        'image_src' => $form['field_meta_tags']['widget'][0]['advanced']['image_src']['#default_value'],
        'og_image' => $form['field_meta_tags']['widget'][0]['open_graph']['og_image']['#default_value'],
        'twitter_cards_image' => $form['field_meta_tags']['widget'][0]['twitter_cards']['twitter_cards_image']['#default_value'],
        'twitter_cards_image_alt' => $form['field_meta_tags']['widget'][0]['twitter_cards']['twitter_cards_image_alt']['#default_value'],
    );

    foreach($modify_custom_metas as $key => $form_val) {
        $original_value = $tags[$key];
        if(empty($form_val) || ($original_value == $form_val)) {
            switch($key) {
                case 'image_src': {
                    $form['field_meta_tags']['widget'][0]['advanced']['image_src']['#default_value'] = '[node:field_una_header_image:entity:image:entity:url]
';
                break;
                }
                case 'og_image': {
                    $form['field_meta_tags']['widget'][0]['open_graph']['og_image']['#default_value'] = '[node:field_una_header_image:entity:image:entity:url]
';
                break;
                }
                case 'twitter_cards_image': {
                    $form['field_meta_tags']['widget'][0]['twitter_cards']['twitter_cards_image']['#default_value'] = '[node:field_una_header_image:entity:image:entity:url]
';
                break;
                }
                case 'twitter_cards_image_alt': {
                    $form['field_meta_tags']['widget'][0]['twitter_cards']['twitter_cards_image_alt']['#default_value'] = '[node:field_una_header_image:entity:name]
';
                break;
                }
            }
        }
    }
  }

  return $form;
}
